services:
  # mongodb:
  #     image: mongo
  #     container_name: mongo
  #     ports:
  #       - "27017:27017"
  #     volumes:
  #       - mongo_data:/data/db
  auth_service:
    build: ./services/auth_service
    ports:
      - "8001:8000"
    environment:
      - MONGO_URI=mongodb+srv://rohankumar6143:143rohan@cluster0.57rhuig.mongodb.net/
