services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - private_net

  auth_service:
    build: ./services/auth_service
    container_name: auth_service
    depends_on:
      - mongodb
    ports:
      - "8000:8000"  # Public port
      - "8002:8002"  # Prometheus port
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - JWT_SECRET=mysecretkey
    networks:
      - private_net

  order_service:
    build: ./services/order_service
    container_name: order_service
    depends_on:
      - mongodb
      - catalog_service
    ports:
      - "8003:8000"  # You can change this as needed
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - CATALOG_SERVICE_URL=http://catalog_service:8001
      - JWT_SECRET=mysecretkey
    networks:
      - private_net

  catalog_service:
    build: ./services/catalog_service
    container_name: catalog_service
    depends_on:
      - mongodb
    ports:
      - "8001:8000"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
    networks:
      - private_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - auth_service
    networks:
      - private_net

# Optional:
# monitoring_api:
#   build: ./monitoring_app/backend
#   ports:
#     - "7000:7000"
#   depends_on:
#     - prometheus
#   networks:
#     - private_net

# monitoring_ui:
#   build: ./monitoring_app/frontend
#   ports:
#     - "3000:3000"
#   depends_on:
#     - monitoring_api
#   networks:
#     - private_net

volumes:
  mongo_data:

networks:
  private_net:
    driver: bridge
