global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8002']
        labels:
          service: 'auth'
  - job_name: 'order_service'
    static_configs:
      - targets: ['order_service:8003']
        labels:
          service: 'order'

  # Add more services here
